#include <iostream>
#include <fstream>
#include <string>
#include <functional>
#include <map>
#include <SFML/Graphics.hpp>
#include "gamestates.hpp"
#include "simplefunction.hpp"
#include "drawable.hpp"
#include "builder.hpp"
#include "player.hpp"
#include "window_part.hpp"
#include "obstacle.hpp"
#include "buttons.hpp"
#include "menu.hpp"
#include "sprite_factory.hpp"
#include "init_game.hpp"
#include "game_screen.hpp"

